/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectorIndexRouteImport } from './routes/director.index'
import { Route as LoginEmployeeRouteImport } from './routes/login.employee'
import { Route as LoginDirectorRouteImport } from './routes/login.director'
import { Route as DirectorEmployeesRouteImport } from './routes/director.employees'

const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorIndexRoute = DirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorRoute,
} as any)
const LoginEmployeeRoute = LoginEmployeeRouteImport.update({
  id: '/login/employee',
  path: '/login/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDirectorRoute = LoginDirectorRouteImport.update({
  id: '/login/director',
  path: '/login/director',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorEmployeesRoute = DirectorEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DirectorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteWithChildren
  '/director/employees': typeof DirectorEmployeesRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/director/': typeof DirectorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director/employees': typeof DirectorEmployeesRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/director': typeof DirectorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteWithChildren
  '/director/employees': typeof DirectorEmployeesRoute
  '/login/director': typeof LoginDirectorRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/director/': typeof DirectorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director'
    | '/director/employees'
    | '/login/director'
    | '/login/employee'
    | '/director/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director/employees'
    | '/login/director'
    | '/login/employee'
    | '/director'
  id:
    | '__root__'
    | '/'
    | '/director'
    | '/director/employees'
    | '/login/director'
    | '/login/employee'
    | '/director/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRoute: typeof DirectorRouteWithChildren
  LoginDirectorRoute: typeof LoginDirectorRoute
  LoginEmployeeRoute: typeof LoginEmployeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/': {
      id: '/director/'
      path: '/'
      fullPath: '/director/'
      preLoaderRoute: typeof DirectorIndexRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/login/employee': {
      id: '/login/employee'
      path: '/login/employee'
      fullPath: '/login/employee'
      preLoaderRoute: typeof LoginEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/director': {
      id: '/login/director'
      path: '/login/director'
      fullPath: '/login/director'
      preLoaderRoute: typeof LoginDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/employees': {
      id: '/director/employees'
      path: '/employees'
      fullPath: '/director/employees'
      preLoaderRoute: typeof DirectorEmployeesRouteImport
      parentRoute: typeof DirectorRoute
    }
  }
}

interface DirectorRouteChildren {
  DirectorEmployeesRoute: typeof DirectorEmployeesRoute
  DirectorIndexRoute: typeof DirectorIndexRoute
}

const DirectorRouteChildren: DirectorRouteChildren = {
  DirectorEmployeesRoute: DirectorEmployeesRoute,
  DirectorIndexRoute: DirectorIndexRoute,
}

const DirectorRouteWithChildren = DirectorRoute._addFileChildren(
  DirectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRoute: DirectorRouteWithChildren,
  LoginDirectorRoute: LoginDirectorRoute,
  LoginEmployeeRoute: LoginEmployeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
