/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as DirectorIndexRouteImport } from './routes/director.index'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as EmployeeArchiveRouteImport } from './routes/employee.archive'
import { Route as DirectorTasksRouteImport } from './routes/director.tasks'
import { Route as DirectorStatsRouteImport } from './routes/director.stats'
import { Route as DirectorFormsRouteImport } from './routes/director.forms'
import { Route as DirectorEmployeesRouteImport } from './routes/director.employees'
import { Route as DirectorClientsRouteImport } from './routes/director.clients'
import { Route as DirectorAttendanceRouteImport } from './routes/director.attendance'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const DirectorIndexRoute = DirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorRoute,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeArchiveRoute = EmployeeArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => EmployeeRoute,
} as any)
const DirectorTasksRoute = DirectorTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorStatsRoute = DirectorStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorFormsRoute = DirectorFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorEmployeesRoute = DirectorEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorClientsRoute = DirectorClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorAttendanceRoute = DirectorAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DirectorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/director/attendance': typeof DirectorAttendanceRoute
  '/director/clients': typeof DirectorClientsRoute
  '/director/employees': typeof DirectorEmployeesRoute
  '/director/forms': typeof DirectorFormsRoute
  '/director/stats': typeof DirectorStatsRoute
  '/director/tasks': typeof DirectorTasksRoute
  '/employee/archive': typeof EmployeeArchiveRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/f/$formId': typeof FFormIdRoute
  '/director/': typeof DirectorIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director/attendance': typeof DirectorAttendanceRoute
  '/director/clients': typeof DirectorClientsRoute
  '/director/employees': typeof DirectorEmployeesRoute
  '/director/forms': typeof DirectorFormsRoute
  '/director/stats': typeof DirectorStatsRoute
  '/director/tasks': typeof DirectorTasksRoute
  '/employee/archive': typeof EmployeeArchiveRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/f/$formId': typeof FFormIdRoute
  '/director': typeof DirectorIndexRoute
  '/employee': typeof EmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/director/attendance': typeof DirectorAttendanceRoute
  '/director/clients': typeof DirectorClientsRoute
  '/director/employees': typeof DirectorEmployeesRoute
  '/director/forms': typeof DirectorFormsRoute
  '/director/stats': typeof DirectorStatsRoute
  '/director/tasks': typeof DirectorTasksRoute
  '/employee/archive': typeof EmployeeArchiveRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/f/$formId': typeof FFormIdRoute
  '/director/': typeof DirectorIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director'
    | '/employee'
    | '/director/attendance'
    | '/director/clients'
    | '/director/employees'
    | '/director/forms'
    | '/director/stats'
    | '/director/tasks'
    | '/employee/archive'
    | '/employee/attendance'
    | '/employee/tasks'
    | '/f/$formId'
    | '/director/'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director/attendance'
    | '/director/clients'
    | '/director/employees'
    | '/director/forms'
    | '/director/stats'
    | '/director/tasks'
    | '/employee/archive'
    | '/employee/attendance'
    | '/employee/tasks'
    | '/f/$formId'
    | '/director'
    | '/employee'
  id:
    | '__root__'
    | '/'
    | '/director'
    | '/employee'
    | '/director/attendance'
    | '/director/clients'
    | '/director/employees'
    | '/director/forms'
    | '/director/stats'
    | '/director/tasks'
    | '/employee/archive'
    | '/employee/attendance'
    | '/employee/tasks'
    | '/f/$formId'
    | '/director/'
    | '/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRoute: typeof DirectorRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  FFormIdRoute: typeof FFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/director/': {
      id: '/director/'
      path: '/'
      fullPath: '/director/'
      preLoaderRoute: typeof DirectorIndexRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/archive': {
      id: '/employee/archive'
      path: '/archive'
      fullPath: '/employee/archive'
      preLoaderRoute: typeof EmployeeArchiveRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/director/tasks': {
      id: '/director/tasks'
      path: '/tasks'
      fullPath: '/director/tasks'
      preLoaderRoute: typeof DirectorTasksRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/stats': {
      id: '/director/stats'
      path: '/stats'
      fullPath: '/director/stats'
      preLoaderRoute: typeof DirectorStatsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/forms': {
      id: '/director/forms'
      path: '/forms'
      fullPath: '/director/forms'
      preLoaderRoute: typeof DirectorFormsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/employees': {
      id: '/director/employees'
      path: '/employees'
      fullPath: '/director/employees'
      preLoaderRoute: typeof DirectorEmployeesRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/clients': {
      id: '/director/clients'
      path: '/clients'
      fullPath: '/director/clients'
      preLoaderRoute: typeof DirectorClientsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/attendance': {
      id: '/director/attendance'
      path: '/attendance'
      fullPath: '/director/attendance'
      preLoaderRoute: typeof DirectorAttendanceRouteImport
      parentRoute: typeof DirectorRoute
    }
  }
}

interface DirectorRouteChildren {
  DirectorAttendanceRoute: typeof DirectorAttendanceRoute
  DirectorClientsRoute: typeof DirectorClientsRoute
  DirectorEmployeesRoute: typeof DirectorEmployeesRoute
  DirectorFormsRoute: typeof DirectorFormsRoute
  DirectorStatsRoute: typeof DirectorStatsRoute
  DirectorTasksRoute: typeof DirectorTasksRoute
  DirectorIndexRoute: typeof DirectorIndexRoute
}

const DirectorRouteChildren: DirectorRouteChildren = {
  DirectorAttendanceRoute: DirectorAttendanceRoute,
  DirectorClientsRoute: DirectorClientsRoute,
  DirectorEmployeesRoute: DirectorEmployeesRoute,
  DirectorFormsRoute: DirectorFormsRoute,
  DirectorStatsRoute: DirectorStatsRoute,
  DirectorTasksRoute: DirectorTasksRoute,
  DirectorIndexRoute: DirectorIndexRoute,
}

const DirectorRouteWithChildren = DirectorRoute._addFileChildren(
  DirectorRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeArchiveRoute: typeof EmployeeArchiveRoute
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeArchiveRoute: EmployeeArchiveRoute,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRoute: DirectorRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  FFormIdRoute: FFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
